# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-08 07:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yaksh', '0015_course_view_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='language',
            field=models.CharField(choices=[('python', 'Python'), ('bash', 'Bash'), ('c', 'C Language'), ('cpp', 'C++ Language'), ('java', 'Java Language'), ('scilab', 'Scilab'), ('english', 'English'), ('physics', 'Physics'), ('chemistry', 'Chemistry'), ('maths', 'Mathematics'), ('biology', 'Biology'), ('machineLearning', 'Machine Learning')], max_length=24),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('mcq', 'Single Correct Choice'), ('mcc', 'Multiple Correct Choices'), ('text', 'Text Area'), ('upload', 'Assignment Upload'), ('integer', 'Answer in Integer'), ('string', 'Answer in String'), ('float', 'Answer in Decimals'), ('arrange', 'Arrange in Correct Order')], max_length=24),
        ),
        migrations.AlterField(
            model_name='questionpaper',
            name='random_questions',
            field=models.ManyToManyField(blank=True, null=True, to='yaksh.QuestionSet'),
        ),
    ]
